### ISSUE TITLE
Any documentation for connecting Terminal Payment in windows

### ISSUE THREAD

**Issue by flotho** [akretion/pywebdriver#115]
Hi,

Is there any tips regarding the set up of protocol telium on windows?

Regards

**Comment by flotho** [comment]
also related to #50

**Comment by PierrickBrun** [comment]
Hi,

I don't think anyone uses telium on windows for now so it may be needed to fix some code to make it work.

Once pywebdriver has been installed on windows, the `config.ini` file should be modified to include the following:
 - In the `drivers` line of the `application` category add `,telium_driver` at the end of the line
 - In the `device_name` line of the `telium_driver` category you will probably need to replace `auto` by the serial port assigned to it by windows (something like `COM1`, `COM2`, `COM3`...). You can find it in the peripherals menu (I think you need to activate a "show hidden peripherals" option but I'm not on windows so I can't check)

About the terminal's setup, follow this readme: https://github.com/akretion/pypostelium

**Comment by legalsylvain** [comment]
Hi @flotho. Today, I tried to installed pywebdriver on windows with payment terminal. It was not working, because the installation of pypostelium was disabled in the requirements of windows installation.
This patch https://github.com/akretion/pywebdriver/pull/139 fixed the problem and telium protocol is now available on Windows.
Closing.

**Comment by flotho** [comment]
greaatttt
