### ISSUE TITLE
Is pywebdriver an API REST with Flaskful ?

### ISSUE THREAD

**Issue by JuanDCG** [akretion/pywebdriver#90]

**Comment by legalsylvain** [comment]
It's a flask app, but we didn't implemented api rest.

What is your need ?

**Comment by JuanDCG** [comment]
Integrate pywebdriver as RESTful enpoints with OCA/iot ?

¿?¿?¿? I suggest it.


https://flask-restful.readthedocs.io/en/latest/quickstart.html#endpoints

https://github.com/OCA/iot

**Comment by legalsylvain** [comment]
@sebastienbeau, @PierrickBrun : any insight ?

**Comment by JuanDCG** [comment]
I don't know if this is possible or have convenience

**Comment by PierrickBrun** [comment]
At the moment this is not a RESTful API as pywebdriver mimics the endpoints used by Odoo PoS, which is not really RESTful.

That said, I think this is possible since pywebdriver uses Flask.

But I'm not sure if this a the best bet, pywebdriver has a lot of dependencies that may make it too heavy in an IoT context. Maybe a solution would be to have separate builds for iot-pywebdriver and pos-pywebdriver.

**Comment by JuanDCG** [comment]
Ok, I think it because already use Flask framework, so add Flask-RESTful maybe would be possible, but I don't view your code and I don't know how pywebdriver works.

You are the decision maker and you can estimate if it should be possible, and what is the best approach.

Here, an issue that wants a client:

https://github.com/OCA/iot/issues/51

So, I only propose it to integrate all around odoo, pos, iot.
